---
- name: Playbook A - Create a shared file
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check id
      command: id

    - name: Print permissions
      command: ls -l /mnt

    - name: Create a file
      ansible.builtin.copy:
        content: "This data was created by Playbook A at anime"
        dest: mission_data.txt

    - name: Create a file on the persistent volume
      ansible.builtin.copy:
        content: "This data was created by Playbook A at anime"
        dest: /mnt/share/mission_data.txt